-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME, B.중성화
FROM ANIMAL_INS AS A 
JOIN 
(SELECT ANIMAL_ID, IF(SEX_UPON_INTAKE LIKE('Neutered%') OR SEX_UPON_INTAKE LIKE('Spayed%'), 'O', 'X') AS 중성화
 FROM ANIMAL_INS) AS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY ANIMAL_ID ASC;
 