-- 코드를 입력하세요
SELECT T.ANIMAL_ID, T.NAME
FROM
(SELECT A.ANIMAL_ID, A.NAME, TIMESTAMPDIFF(SECOND, B.DATETIME, A.DATETIME) AS X
FROM ANIMAL_OUTS AS A LEFT JOIN ANIMAL_INS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NOT NULL) AS T
ORDER BY T.X DESC
LIMIT 2;